export const status = [
  {
    bridge: "swing",
    createdAt: "occaecat officia id ea ad",
    fallbackAmount: "velit qui sint minim Duis",
    fallbackTokenAddress: "dolor nulla",
    fromAmount: "in ut quis voluptate",
    fromAmountUsdValue: "consectetur voluptate id",
    fromChainId: 12391662.485217214,
    fromChainSlug: "moonbeam",
    fromChainTxHash: "labore do",
    fromTokenAddress: "est Lorem",
    fromTokenSymbol: "ipsum incididunt occaecat",
    fromUserAddress: "occaecat voluptate ex sint deserunt",
    id: 42358415.069141656,
    needClaim: false,
    refundReason: "fugiat",
    status: "Submitted",
    toAmount: "magna id ex dolor et",
    toAmountUsdValue: "irure dolor commodo",
    toChainId: 61023527.79052925,
    toChainSlug: "fuse",
    toChainTxHash: "deserunt nostrud in anim adipisicing",
    toTokenAddress: "culpa officia minim elit",
    toTokenSymbol: "tempor pariatur exercitation commodo Duis",
    toUserAddress: "sit aliquip enim",
    txCompletedTimestamp: 68734381.04347476,
    txId: "nisi id Lorem enim pariatur",
    txStartedTimestamp: 57917420.50222877,
    updatedAt: "exercitation",
  },
  {
    bridge: "multichain",
    createdAt: "cillum consectetur",
    fallbackAmount: "dolore et dolor",
    fallbackTokenAddress: "sit proident",
    fromAmount: "occaecat irure velit ut ex",
    fromAmountUsdValue: "tempor velit laboris exercitation",
    fromChainId: 53626441.51200819,
    fromChainSlug: "harmony",
    fromChainTxHash: "Lorem anim fugiat amet do",
    fromTokenAddress: "Ut fugiat",
    fromTokenSymbol: "enim ex anim labore ipsum",
    fromUserAddress: "irure",
    id: 21979223.61563331,
    needClaim: true,
    refundReason: "sunt magna",
    status: "Not Sent",
    toAmount: "irure",
    toAmountUsdValue: "laboris",
    toChainId: 7692422.123157352,
    toChainSlug: "axelar",
    toChainTxHash: "ex ut laborum",
    toTokenAddress: "consequat ea amet Duis",
    toTokenSymbol: "laboris",
    toUserAddress: "ipsum",
    txCompletedTimestamp: 20962620.55640392,
    txId: "est laboris consequat",
    txStartedTimestamp: -64570390.50739848,
    updatedAt: "Ut occaecat nulla enim aliquip",
  },
  {
    bridge: "multiversx",
    createdAt: "fugiat",
    fallbackAmount: "nostrud pariatur et",
    fallbackTokenAddress: "est elit",
    fromAmount: "occaecat consectetur",
    fromAmountUsdValue: "laboris non",
    fromChainId: 96100935.05897325,
    fromChainSlug: "fuse",
    fromChainTxHash: "in aliquip",
    fromTokenAddress: "tempor est et eu consequat",
    fromTokenSymbol: "aliqua dolore do",
    fromUserAddress: "ex nisi elit ipsum est",
    id: 39505581.05778566,
    needClaim: false,
    refundReason: "commodo anim aliquip",
    status: "Completed",
    toAmount: "adipisicing",
    toAmountUsdValue: "ad ex pariatur anim nisi",
    toChainId: -79191642.23410307,
    toChainSlug: "fuse",
    toChainTxHash: "sed deserunt aute ut",
    toTokenAddress: "non",
    toTokenSymbol: "sunt magna in",
    toUserAddress: "do veniam",
    txCompletedTimestamp: 73792599.97013122,
    txId: "ut et",
    txStartedTimestamp: -45103224.7379799,
    updatedAt: "ipsum aute magna",
  },
  {
    bridge: "celer",
    createdAt: "ea et",
    fallbackAmount: "incididunt eu ut sit",
    fallbackTokenAddress: "Excepteur ad voluptate amet",
    fromAmount: "cillum Lorem",
    fromAmountUsdValue: "qui magna",
    fromChainId: 25237466.063094378,
    fromChainSlug: "msx",
    fromChainTxHash: "nisi id",
    fromTokenAddress: "aliqua in",
    fromTokenSymbol: "adipisicing labore incididunt consectetur ut",
    fromUserAddress: "in adipisicing consequat commodo culpa",
    id: -79882053.46632741,
    needClaim: false,
    refundReason: "eu exercitation sed fugiat do",
    status: "Refund Required",
    toAmount: "dolor enim culpa exercitation",
    toAmountUsdValue: "voluptate est aute elit",
    toChainId: -8889677.55718486,
    toChainSlug: "bttc",
    toChainTxHash: "voluptate",
    toTokenAddress: "laborum enim irure",
    toTokenSymbol: "voluptate",
    toUserAddress: "enim sed qui ullamco labore",
    txCompletedTimestamp: -5504119.726069808,
    txId: "enim voluptate fugiat adipisicing qui",
    txStartedTimestamp: 98706945.18068719,
    updatedAt: "elit pariatur esse fugiat amet",
  },
];
